name: 'GHA Build Vars'
author: 'Pinal Bhatt'
description: 'Gets Env Variables for Growth Builds'
inputs:
  pkgJsonLocation:
    description: 'Path of package.json'
    default: './'
outputs:
  branchName:
    description: branch name
  packageVersionTag:
    description: package version tag
  packageVersion:
    description: package version
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'dollar-sign'
  color: 'blue'
