name: 'GHA Build Vars'
author: 'Pinal Bhatt'
description: 'Gets Env Variables for Growth Builds'
inputs:
  pkgJsonLocation:
    description: 'Path of package.json'
    default: './'
  shortSHALength:
    description: length of short SHA
    default: '7'
outputs:
  branchName:
    description: branch name
  branchTag:
    description: branch tag
  shortSHA:
    description: short SHA
  versionTag:
    description: package version tag
  packageVersion:
    description: package version
  releaseBranch:
    description: name of release branch
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'dollar-sign'
  color: 'blue'
